[package]
name = "tokio-select-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
tokio = { version = "1.29", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
